#!/bin/sh
if [ "x$1" = "xauto" ] ; then
    ID=auto
    if [ -n "$DRONE_BUILD_NUMBER" ] ; then
        ID=$DRONE_BUILD_NUMBER
    fi
    exec /app/bin/sc --verbose --tunnel-identifier $ID
fi
exec /app/bin/sc "$@"
